package com.example.materialreviews.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Colori generati da https://material-foundation.github.io/material-theme-builder/#/custom
val md_theme_light_primary = Color(0xFFb52327)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdad5)
val md_theme_light_onPrimaryContainer = Color(0xFF410003)
val md_theme_light_secondary = Color(0xFF775653)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffdad7)
val md_theme_light_onSecondaryContainer = Color(0xFF2c1513)
val md_theme_light_tertiary = Color(0xFF725b2e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdea6)
val md_theme_light_onTertiaryContainer = Color(0xFF271900)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a19)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a19)
val md_theme_light_surfaceVariant = Color(0xFFf4dddb)
val md_theme_light_onSurfaceVariant = Color(0xFF524342)
val md_theme_light_outline = Color(0xFF857371)
val md_theme_light_inverseOnSurface = Color(0xFFfbeeec)
val md_theme_light_inverseSurface = Color(0xFF362f2e)
val md_theme_light_inversePrimary = Color(0xFFffb3ab)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffb3ab)
val md_theme_dark_onPrimary = Color(0xFF680008)
val md_theme_dark_primaryContainer = Color(0xFF930013)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdad5)
val md_theme_dark_secondary = Color(0xFFe7bdb9)
val md_theme_dark_onSecondary = Color(0xFF442a28)
val md_theme_dark_secondaryContainer = Color(0xFF5d3f3d)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdad7)
val md_theme_dark_tertiary = Color(0xFFe1c28c)
val md_theme_dark_onTertiary = Color(0xFF402d05)
val md_theme_dark_tertiaryContainer = Color(0xFF584319)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdea6)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a19)
val md_theme_dark_onBackground = Color(0xFFecdfde)
val md_theme_dark_surface = Color(0xFF201a19)
val md_theme_dark_onSurface = Color(0xFFecdfde)
val md_theme_dark_surfaceVariant = Color(0xFF524342)
val md_theme_dark_onSurfaceVariant = Color(0xFFd7c1bf)
val md_theme_dark_outline = Color(0xFFa08c8a)
val md_theme_dark_inverseOnSurface = Color(0xFF201a19)
val md_theme_dark_inverseSurface = Color(0xFFecdfde)
val md_theme_dark_inversePrimary = Color(0xFFb52327)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF930013)
val error = Color(0xFFba1b1b)